### PR TITLE
Fails on empty comments without 4 -"

### LINKED ISSUE #604: Panic when parsing invalid comments `<!-->`
On the following input quick XML 0.28-2 panics with ` 'slice index starts at 3 but ends at 1', quick-xml-0.28.2/src/reader/parser.rs:104:22`

```xml
<?xml version="1.0" encoding="utf-8"?>
<sparql xmlns="http://www.w3.org/2005/sparql-resu:lts#">
<head>
        <variable name="str"/>
</head>
<results>
        <result></result> <!-->
        <result></resulhtmlns>=
```

I believe this error is caused by [this line](https://github.com/tafia/quick-xml/blob/84b07b4e5c9a201b3d3d7fa95c1e8c33ecbe6dd2/src/reader/mod.rs#L828) where the `buf.len() + i > 4` check is wrong.

### PR DESCRIPTION
**Pull request by Tpt**
The parser was crashing because of bad slice bounds

Closes #604

### CODE REVIEW

File: tests/fuzzing.rs [hunk 1]
```diff
@@ -60,3 +60,29 @@ fn fuzz_empty_doctype() {
     ));
     assert_eq!(reader.read_event_into(&mut buf).unwrap(), Event::Eof);
 }
+
+#[test]
+fn fuzz_empty_comment() {
```
Comment (Mingun) [inline tests/fuzzing.rs:65]: I think, it would be better to place tests to `tests/issues.rs` file. Also, could you check that we actually returns `UnexpectedToken("<!-->")`? That is, explicitly expect all the events that the parser returns:
```rust
assert_eq!(reader.read_event_into(&mut buf), Ok(...));
assert_eq!(reader.read_event_into(&mut buf), Ok(...));
// and so on
```

File: src/reader/parser.rs [hunk 2]
```diff
@@ -100,6 +100,10 @@ impl Parser {
                         return Err(Error::UnexpectedToken("--".to_string()));
                     }
                 }
+                if len < 5 {
+                    // We do not have any text content
+                    return Err(Error::UnexpectedToken("<!-->".to_string()));
```
Comment (Mingun) [inline src/reader/parser.rs:105]: I think, it would be better to write something more descriptive, because this path will be taken also for the `<!--->` input and having `<!-->` in the error could be misleading. Maybe even introduce a new error variant specially for that case (`NotClosedComment`, for example)

**Review by Mingun — CHANGES_REQUESTED** [review]
I think that approach is good, but we need more bullet-proof tests that will actually test that we take this code path (by checking actual events).

**Comment by Mingun** [comment]
Actually, fix of this issue not so simple. `<!-->-->` is a valid XML (see https://github.com/tafia/quick-xml/issues/258#issuecomment-1586322843)

File: tests/fuzzing.rs (hunk 1 above)
Comment (Tpt) [reply tests/fuzzing.rs]: Indeed. Done.

File: src/reader/parser.rs (hunk 2 above)
Comment (Tpt) [reply src/reader/parser.rs]: I have changed approach. I am not creating new error with the new approach. The new error message is not great but I believe it is for an other PR and not this one. Would you be ok with that?

**Comment by Tpt** [comment]
> Actually, fix of this issue not so simple.  is a valid XML (see https://github.com/tafia/quick-xml/issues/258#issuecomment-1586322843)

Indeed. Thank you for spotting this! I have found a cleaner way to fix the bug that behaves properly in this case.

File: tests/issues.rs [hunk 3]
```diff
@@ -105,3 +105,51 @@ mod issue514 {
         assert_eq!(reader.read_event().unwrap(), Event::Eof);
     }
 }
+
+#[test]
+fn issue_604_short() {
```
Comment (Mingun) [inline tests/issues.rs:110]: Please put all tests in a module, like as above. Prefix in names not needed because they will be in a module

File: tests/issues.rs [hunk 4]
```diff
@@ -105,3 +105,51 @@ mod issue514 {
...
+    let data = b"<?xml version=\"1.0\" encoding=\"utf-8\"?><!-->";
+    let mut reader = Reader::from_reader(data.as_slice());
+    let mut buf = Vec::new();
+    assert!(matches!(
+        reader.read_event_into(&mut buf),
+        Ok(Event::Decl(_))
+    ));
```
Comment (Mingun) [inline tests/issues.rs:117]: Use `assert_eq!()` + `unwrap()` for `Ok` results, like as above. `assert_eq!()` is from `pretty_assertions` crate which will print a nice diff in case of error

File: src/reader/parser.rs (hunk 2 above)
Comment (Mingun) [reply src/reader/parser.rs]: Yes, that is OK. We need to rework our errors anyway

File: tests/issues.rs [hunk 5]
```diff
@@ -105,3 +105,51 @@ mod issue514 {
...
+    assert!(matches!(
+        reader.read_event_into(&mut buf),
+        Err(Error::UnexpectedEof(_))
+    ));
+    assert!(matches!(reader.read_event_into(&mut buf), Ok(Event::Eof)));
+}
+
+#[test]
+fn issue_604_valid() {
+    let data = b"<?xml version=\"1.0\" encoding=\"utf-8\"?><!-->-->";
```
Comment (Mingun) [inline tests/issues.rs:143]: Could you also add a test for `<!--->-->`?

**Review by Mingun — CHANGES_REQUESTED** [review]
Almost good, thanks! I left several comments

**Comment by Tpt** [comment]
Thank you! I have updated the tests following your review!

**Review by Mingun — APPROVED** [review]
Approved, but I'd like to postpone merging until I'll get idea how it is working

File: src/reader/buffered_reader.rs [hunk 6]
```diff
@@ -117,7 +117,7 @@ macro_rules! impl_buffered_source {
                     // somewhere sane rather than at the EOF
                     Ok(n) if n.is_empty() => return Err(bang_type.to_err()),
                     Ok(available) => {
-                        if let Some((consumed, used)) = bang_type.parse(buf, available) {
+                        if let Some((consumed, used)) = bang_type.parse(&buf[start..], available) {
```
[the remark this answers is not in the document]
Comment (Mingun) [reply src/reader/buffered_reader.rs:120]: I think, I understood. We should parse only newly read data from the `buf`. This is correct, because we in the function that parses the whole comment, so any data that exists in the buffer before is not relevant here and should be skipped.

[the remark this answers is not in the document]
Comment (Tpt) [reply src/reader/buffered_reader.rs:122]: Yes, exactly. I have added the comment. Not doing so was making some checks like [the one on this line](https://github.com/tafia/quick-xml/blob/60249aeea24bfe00848a70950ae7cd321cacfb3c/src/reader/mod.rs#L828) to be incorrect.

**Comment by Mingun** [comment]
Thanks! I slightly changed tests to more precisely test what an error we returns and changed Changelog description to be less technically specific and more user specific
