### PR TITLE
Fix incorrect deserialization of vectors of enums from sequences of tags

### LINKED ISSUE #567: `Unexpected Event::End(...)` or `missing field '...'`
Hello dear maintainers

I'm trying to alter [`ethercat-esi`](https://github.com/ethercat-rs/ethercat-esi) to use `quick_xml` instead of `serde-xml-rs`. This is pretty straight forward as `ethercat-esi` crate is only using the `serde` macros and calling the xml parser at one place.
```rust 
// ethercat-esi//src/lib.rs
let raw_info: parser::EtherCATInfo = quick_xml::de::from_str(xml)
            .map_err(|e| Error::new(ErrorKind::Other, e.to_string()))?;
```
Running this code (in lib or in a test file of that crate) gives me the following output on both xml files
```rust
$ target/debug/test/some ~/erob-custom.xml
Error: Custom { kind: Other, error: "Unexpected `Event::End(\"Groups\")`" }

// then I comment the Groups section in the xml
$ target/debug/test/some ~/erob-custom.xml
Error: Custom { kind: Other, error: "missing field `ProductCode`" }

// then I change quick-xml version from v0.27.1 to v0.26.0
$ target/debug/test/some ~/erob-custom.xml
Error: Custom { kind: Other, error: "missing field `Sm`" }
```

These fields and the Groups markups are good in the xml files. And it doesn't seems to come from the serde declarations of the xml data (in `ethercat-esi/src/mod.rs`), so I suggest there is an issue with the way the `quick_xml` functions are calling or checking results of the serde deserialization functions. (especially since the error is not the same depending on the version of `quick_xml`)
How do you think I could solve this problem ?

### PR DESCRIPTION
**Pull request by Mingun**
This PR fixes #567 which is an instance of generic problem, where top-level deserializer used to deserialize elements inside `<tags>`. It changes things in that way that correct deserializer is used to deserialize types.

The diagram below shows how each struct is related to each other in this PR (`SimpleTypeDeserializer` has more usages, not all of them shown in order to keep diagram small):
```mermaid
flowchart TD
    Deserializer --maps and structs--> ElementMapAccess
    ElementMapAccess --for $text field--> SimpleTypeDeserialzier
    ElementMapAccess --for each field--> MapValueDeserializer
    MapValueDeserializer --for sequences--> MapValueSeqAccess
    MapValueSeqAccess --DeEvent::Start--> ElementDeserializer
    MapValueSeqAccess --DeEvent::Text--> TextDeserializer
    ElementDeserializer --maps and structs--> ElementMapAccess
    TextDeserializer --> SimpleTypeDeserialzier
```

Most commits are prepare work, [the actual fix](https://github.com/tafia/quick-xml/commit/74cd2726ae065bea88eed182e5ceea8388563629#diff-529c3affb2cf6fde2450b68cc6d8ddc24ef85fca368a517310a07cb0cd71b820R1021) is just one line change and yet another for consistence (and I believe also fixes some bug).

The last four commits just some cleanup work, but important because it adds documentation how deserializers work and what is their difference from each other.

### CODE REVIEW

File: src/de/map.rs [hunk 1]
```diff
@@ -605,6 +582,41 @@ where
...
+        self,
+        _name: &'static str,
+        _variants: &'static [&'static str],
+        visitor: V,
+    ) -> Result<V::Value, Self::Error>
+    where
+        V: Visitor<'de>,
+    {
+        visitor.visit_enum(crate::de::var::EnumAccess::new(self.map.de))
+    }
```
Comment (Mingun) [inline src/de/map.rs:609]: This call also incorrect, because it will use top-level deserializer for deserializing newtype variants, for example, but I leave fixing that for separate PR. We do not have tests for this situation yet, and I want to approve each change by tests that failed before and pass after the change.
