### PR TITLE
Fix #435: replay only events from time of creating SeqAccess struct

### LINKED ISSUE #435: Missing field "StructuredType"
Here is my xml file:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<opc:TypeDictionary
  xmlns:opc="http://opcfoundation.org/BinarySchema/"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:ua="http://opcfoundation.org/UA/"
  xmlns:tns="http://opcfoundation.org/UA/"
  DefaultByteOrder="LittleEndian"
  TargetNamespace="http://opcfoundation.org/UA/"
>
  <opc:EnumeratedType Name="NodeIdType" LengthInBits="6">
    <opc:Documentation>The possible encodings for a NodeId value.</opc:Documentation>
    <opc:EnumeratedValue Name="TwoByte" Value="0" />
    <opc:EnumeratedValue Name="FourByte" Value="1" />
    <opc:EnumeratedValue Name="Numeric" Value="2" />
    <opc:EnumeratedValue Name="String" Value="3" />
    <opc:EnumeratedValue Name="Guid" Value="4" />
    <opc:EnumeratedValue Name="ByteString" Value="5" />
  </opc:EnumeratedType>
  
  <opc:StructuredType Name="TwoByteNodeId">
    <opc:Field Name="Identifier" TypeName="opc:Byte" />
  </opc:StructuredType>

  <opc:StructuredType Name="FourByteNodeId">
    <opc:Field Name="NamespaceIndex" TypeName="opc:Byte" />
    <opc:Field Name="Identifier" TypeName="opc:UInt16" />
  </opc:StructuredType>

  <opc:EnumeratedType Name="AxisScaleEnumeration" LengthInBits="32">
    <opc:EnumeratedValue Name="Linear" Value="0" />
    <opc:EnumeratedValue Name="Log" Value="1" />
    <opc:EnumeratedValue Name="Ln" Value="2" />
  </opc:EnumeratedType>

  <opc:EnumeratedType Name="ExceptionDeviationFormat" LengthInBits="32">
    <opc:EnumeratedValue Name="AbsoluteValue" Value="0" />
    <opc:EnumeratedValue Name="PercentOfValue" Value="1" />
    <opc:EnumeratedValue Name="PercentOfRange" Value="2" />
    <opc:EnumeratedValue Name="PercentOfEURange" Value="3" />
    <opc:EnumeratedValue Name="Unknown" Value="4" />
  </opc:EnumeratedType>
</opc:TypeDictionary>

```
My rust code:
```rust
#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct TypeDictionary {
    #[serde(rename = "StructuredType")]
    pub struct_types: Vec<StructType>,

    #[serde(rename = "EnumeratedType")]
    pub enum_types: Vec<EnumType>,
}

#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct StructType {
    #[serde(rename = "Name")]
    pub name: String,

    #[serde(rename = "Documentation")]
    pub documentation: Option<String>,

    #[serde(rename = "BaseType")]
    pub base_type: Option<String>,

    #[serde(rename = "Field", default)]
    pub fields: Vec<StructField>,
}

#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct StructField {
    #[serde(rename = "Name", default)]
    pub name: String,

    #[serde(rename = "TypeName")]
    pub type_name: String,

    #[serde(rename = "Length")]
    pub length: Option<String>,

    #[serde(rename = "LengthField")]
    pub length_field: Option<String>,

    #[serde(rename = "SwitchField")]
    pub switch_field: Option<String>,

    #[serde(rename = "SwitchValue")]
    pub switch_value: Option<String>,

    #[serde(skip)]
    pub is_enum: bool,
}

#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct EnumType {
    #[serde(rename = "Name", default)]
    pub name: String,

    #[serde(rename = "Documentation")]
    pub documentation: Option<String>,

    #[serde(rename = "LengthInBits")]
    pub length_in_bits: Option<String>,

    #[serde(rename = "EnumeratedValue")]
    pub enumerated_values: Vec<EnumValue>,

    #[serde(rename = "IsOptionSet")]
    pub is_option_set: Option<String>,
}

#[derive(Debug, Serialize, Deserialize, PartialEq)]
pub struct EnumValue {
    #[serde(rename = "Name", default)]
    pub name: String,

    #[serde(rename = "Value")]
    pub value: String,
}

pub fn gen_types<P: AsRef<Path> + Copy>(path: P) {
    let p = Path::new("../schemas/1.0.4/Opc.Ua.Types.bsd.xml");
    let data = fs::read_to_string(p);
    let r: Result<TypeDictionary, DeError> = quick_xml::de::from_str(data.unwrap().as_str());
    match r {
        Ok(td) => {
            let struct_types = td.struct_types;
            let enum_types = td.enum_types;
            gen_structs(struct_types, path);
            gen_enums(enum_types, path.as_ref());
        }
        Err(e) => {
            println!("{:?}", e)
        }
    }
}

```

Then an error happend:  ` Custom("missing field `StructuredType`")`

### PR DESCRIPTION
**Pull request by Mingun**
This PR fixes #435. The reason of the bug is that nested lists produces two calls of `start_replay()` of skipped events, but not all events should be replayed after first call.

This PR add marks that determines which events should be replayed after calling `start_replay()`. The mark is created when new replay scope is started (when `deserialize_seq` / `deserialize_tuple` / `deserialize_tuple_struct` is called) and used when `start_replay()` is called.

### CODE REVIEW

File: src/de/mod.rs [hunk 1]
```diff
@@ -1203,6 +1204,195 @@ mod tests {
...
+                        <skipped-4/>
+                        <target-2/>
+                    </inner>
+                    <target-1/>
+                </root>
+                "#,
+            );
+
+            // Initial conditions - both are empty
+            assert_eq!(de.read, vec![]);
```
Comment (dralley) [inline src/de/mod.rs:1256]: Just `.is_empty()` is cleaner

Comment (Mingun) [reply src/de/mod.rs:1256]: I would like to keep comparing with empty vector for two reasons:
- keep uniformity of checks in the test
- if check failed, I would see actual content of a field

**Comment by Mingun** [comment]
I remembered that I've implemented not all tests which I wish

**Review by dralley — APPROVED** [review]
