### PR TITLE
Return an error on empty doctype

### LINKED ISSUE #608: Debug assertion triggered on empty doctype
Thank you for quick-xml and sorry for comming back with an other bug.

When parsing the file `<!DoctyPE>` using rusc "dev" profile the assertion `"DocType must have a name"` is triggered. In the "release" profile the assertion is not triggered and the parser returns an empty `Event::Doctype()`

Test failing in "dev" profile and passing in "release" profile:
```rust
#[test]
fn reproduce() {
    let data = b"<!DoctyPE>";
    let mut reader = Reader::from_reader(data.as_slice());
    let mut buf = Vec::new();
    loop {
        match reader.read_event_into(&mut buf) {
            Ok(Event::Eof) => break,
            Ok(Event::DocType(e)) => assert!(e.is_empty()), // assertion only executed in "release" mode
            _ => unreachable!()
        }
    }
}
```

### PR DESCRIPTION
**Pull request by Tpt**
The parser was crashing with debug assertions enabled but passing with debug assertions disabled

Closes #608

### CODE REVIEW

File: src/errors.rs [hunk 1]
```diff
@@ -37,6 +37,8 @@ pub enum Error {
     /// `Event::BytesDecl` must start with *version* attribute. Contains the attribute
     /// that was found or `None` if an xml declaration doesn't contain attributes.
     XmlDeclWithoutVersion(Option<String>),
+    /// Empty `Event::DocType`.
+    EmptyDocType,
```
Comment (Mingun) [inline src/errors.rs:41]: I suggest to expand description a bit by showing an example of incorrect and correct declarations:
- `<!doctype>` is incorrect
- `<!doctype >` is correct
- `<!doctype sometype>` is correct

**Review by Mingun — CHANGES_REQUESTED** [review]
Need to run `cargo fmt` and please add a changelog entry.

File: src/errors.rs (hunk 1 above)
Comment (Tpt) [reply src/errors.rs]: Thank you! Done.
