### PR TITLE
Handle '>' in attribute values

### LINKED ISSUE #34: Attributes with `>` character are not properly managed
Broken tests:
https://github.com/tafia/quick-xml/blob/master/tests/xmlrs_reader_tests.rs#L45-L80

### PR DESCRIPTION
**Pull request by chklauser**
When looking for the end of a start/empty tag, we use an alternate
version of `read_until` that employs a small state machine to *not*
match on the end byte ('>') when we are currently in an attribute
value.

Fixes #34

I didn't re-enable the tests mentioned in the issue because they would then fail for other reasons. First because of the comment that seems to be parsed correctly but doesn't appear in the test and then because the CData section doesn't match the expected Text event. `quick-xml`s behaviour seems correct.

### CODE REVIEW

**Comment by chklauser** [comment]
The updated version includes a mention of the fix in the changelog.

File: src/lib.rs [hunk 1]
```diff
@@ -873,6 +915,81 @@ fn read_until<R: BufRead>(r: &mut R, byte: u8, buf: &mut Vec<u8>)
...
+                Err(e) => return Err(Error::Io(e)),
+            };
+
+            let mut bytes = available.iter().enumerate();
+
+            let used: usize;
+            loop {
+                match bytes.next() {
+                    Some((i, &b)) => {
+                        if state == ElemReadState::Elem {
```
Comment (tafia) [inline src/lib.rs]: I'd prefer for readability something like
```rust
match (state, b) {
    (ElemReadState::Elem, b) if b == end_byte => { ... },
    (ElemReadState::Elem, b'\'') =>  { ... }, 
    // ...
    (ElemReadState::DoubleQ, b'\"') => { ... }
    _ => (), 
}
```

**Comment by chklauser** [comment]
I have rebased the patch and changed the state machine code to
```rust
state = match (state, b) {
    (ElemReadState::Elem, b) if b == end_byte => {
        // only allowed to match `end_byte` while we are in state `Elem`
        buf.extend_from_slice(&available[..i]);
        done = true;
        used = i + 1;
        break;
    },
    (ElemReadState::Elem,  b'\'') => ElemReadState::SingleQ,
    (ElemReadState::Elem, b'\"') => ElemReadState::DoubleQ,

    // the only end_byte that gets us out of state 'SingleQ' is a single quote
    (ElemReadState::SingleQ, b'\'') => ElemReadState::Elem,

    // the only end_byte that gets us out of state 'DoubleQ' is a double quote
    (ElemReadState::DoubleQ, b'\"') => ElemReadState::Elem,

    // all other bytes: no state change
    _ => state,
};
```
That looks much nicer indeed :)

**Comment by tafia** [comment]
Thanks!
Publishing v0.5.0
