### PR TITLE
Fix wrong disregarding of not closed markup, such as lone `<`

### LINKED ISSUE #622: Invalid close tag is parsed successfully
Parsing the string "><" produces `Event::Text(BytesText { content: Borrowed(">") })` followed by `Event::Eof`. However, this is an invalid XML string, and should result in some kind of error (or detectable error condition).

Reproduction:

```rust
use quick_xml::Reader;
use quick_xml::events::Event;

fn main() {
    
    let mut reader = Reader::from_str("><");
    reader.trim_text(true);
    
    loop {
        let event = reader.read_event().expect("Failed to read event");
        eprintln!("Event: {event:?}");
        if let Event::Eof = event {
            break;
        }
    }
}
```

outputs:

```
Event: Text(BytesText { content: Borrowed(">") })
Event: Eof
```

### PR DESCRIPTION
**Pull request by Mingun**
The 1st commit is a preparation step.
The 2nd adds a regression test.
The 3rd commit fixes #622.

The bug was in two parts:
- the first one is incorrect returning of `Event::Eof` in `read_until_close!` macro. We are inside a markup at this moment, so we cannot return EOF event.
- the second is an incorrect transition to `OpenedTag` state from `ClosedTag` state. It is assumed that in `OpenedTag` we already have seen and have consumed the `<` character, but because `read_byte_until` could return bytes without seeing the searched byte we could go to `OpenedTag` state when `<` was not seen. In that case the first part of a bug have masked problem in most cases.

I also noticed other problems near to fixed code, so the commits 4 and 5 fixes them: `read_element` and `read_bang_element` are called inside of a tag or bang markup (i. e. after seeing `<` character), so they must return a corresponding event or an error. The last commit just a refactoring of that fixes, that also removes dead code arised due to a typo.

### CODE REVIEW

File: src/reader/buffered_reader.rs [hunk 1]
```diff
@@ -90,11 +90,7 @@ macro_rules! impl_buffered_source {
             }
             *position += read;
 
-            if read == 0 {
-                Ok(None)
-            } else {
-                Ok(Some(&buf[start..]))
-            }
+            Ok((&buf[start..], done))
```
Comment (dralley) [inline src/reader/buffered_reader.rs:93]: Maybe I'm missing something.

This code loops while `!done` and only after the loop has exited is there a potential `Ok` return.  Wouldn't the value of `done` therefore always be `true`?

File: src/reader/mod.rs [hunk 2]
```diff
@@ -741,8 +740,8 @@ trait XmlSource<'r, B> {
 
     /// Read input until `byte` is found or end of input is reached.
     ///
-    /// Returns a slice of data read up to `byte`, which does not include into result.
-    /// If input (`Self`) is exhausted, returns `None`.
+    /// Returns a slice of data read up to `byte`, which does not include into result,
```
Comment (dralley) [inline src/reader/mod.rs:746]:
```suggestion
/// Returns a slice of data read up to `byte` (exclusive),
```

File: src/reader/buffered_reader.rs (hunk 1 above)
Comment (dralley) [inline src/reader/buffered_reader.rs:93]: `done` ought to be renamed to `found`

File: src/reader/mod.rs [hunk 3]
```diff
@@ -741,8 +740,8 @@ trait XmlSource<'r, B> {
...
+    /// and a flag was `byte` seen in input or not.
```
Comment (dralley) [inline src/reader/mod.rs:747]:
```suggestion
    /// and a flag noting whether `byte` was found in the input or not.
```

**Review by dralley — APPROVED** [review]

File: src/reader/buffered_reader.rs (hunk 1 above)
Comment (Mingun) [reply src/reader/buffered_reader.rs:93]: Actually, all that code will be removed soon, because I rewrite it, so not necessary to polish it. That changes was made only because I plan to make tests first to know that rewriting did not break anything
