### PR TITLE
Allow attributes in the `Event::End` and fix `.error_position()`

### LINKED ISSUE #776: Parsing malformed closing tags
For [Ruffle](https://ruffle.rs/) it would be useful if we could parse these two kinds of malformed XML:
```xml
<a></a/>
```
From https://github.com/ruffle-rs/ruffle/issues/15674. Note the extra `/`.
```xml
<a></a hello="world">
```
From https://github.com/ruffle-rs/ruffle/issues/16862. Note the attribute in the closing tag!

Excuse me if I missed a config option for this.

### PR DESCRIPTION
**Pull request by Mingun**
This PR allows us to have attributes in the `Event::End` (but they are not accessible via `BytesEnd` directly). As explained in https://github.com/tafia/quick-xml/issues/776#issuecomment-2208078867 we anyway can produce an event which `.name()` does not valid, so it is better ar least keep it useful for some scenarios. When validation API would be added (I'm working on it) we can validate all events and report an error.

Closes #776

When changing parser I noticed, that in one arm we do not set `last_error_offset`. I checked if we really cover that lines -- yes, but we actually does not check anything. `last_error_offset` was checked for `0`, but this is its default value, so was unclear is that code running or not. I improved check and fix the bug that was found due to that.

### CODE REVIEW

File: src/reader/mod.rs [hunk 1]
```diff
@@ -346,18 +346,28 @@ macro_rules! read_until_close {
...
+            // in close tags. While such tags are not allowed by the specification,
+            // we anyway allow to parse them because:
+            // - we do not check constrains during parsing. This is performed by the
+            //   optional validate step which user should call manually
+            // - if we just look for `>` we will parse `</tag attr=">" >` as end tag
+            //   `</tag attr=">` and text `" >` which probably no one existing parser
+            //   do. This is still invalid tag but it also has no practical meaning
+            //   to parse it in a such way. End tag `</tag attr=">" >`, however, can
+            //   be produced by some real-world parsers, for example, by the parser
+            //   of the Macromedia Flash player.
```
Comment (dralley) [inline src/reader/mod.rs:358]: For what it's worth, other "non-validating" parsers like expat still blow up on this

>ExpatError: not well-formed (invalid token): line 1, column 11

Lxml and libxml2 also do

>XMLSyntaxError: expected '>', line 1, column 12

>parserError: xmlParseDoc() failed

I'm on-board with making this possible to support, but our default behavior should probably be throwing an `IllFormedError` just like we do for mismatched tags (and like other parsers do).

>ExpatError: mismatched tag: line 1, column 7

Comment (Mingun) [reply src/reader/mod.rs:358]: I want to evolve library in this direction:
- rename `Reader` to `RawReader` (and `Event` to `RawEvent`)
- make `RawReader` as liberal as possible. It should not make any validation checks
- add a `validate` method to `RawEvent` which will perform all well-formedless and validity checks (I already grab list of all checks from the [specification](https://www.w3.org/TR/xml11), 35 VC + 16 WFC references, actually most of them about DTD). All validation must be run manually by calling `RawEvent::validate`. Only one check cannot be performed in this way: check that [start tag name matches end tag name](https://www.w3.org/TR/xml11/#GIMatch)
- move existing checks (for example, [`IllFormedError::DoubleHyphenInComment`](https://github.com/tafia/quick-xml/blob/22b3e458d193e6937882ba6b643ec8c31a671de5/src/errors.rs#L119C26-L119C27)) to the new `validate` method
- introduce a new `Reader` which will perform validation checks when flag in config is set (and process many other things, like dealing with encodings and expanding entity references as shown in the `custom_entities` example in #766). Add necessary config flags

I haven't thought through all the details yet and don't want to focus on them yet. There will be a separate PR where all this will be considered. It should be pretty soon (this year).

So, given that we are not currently performing most validity checks and I am planning a generic consistent solution for them, do you agree that it is not worth introducing them now?

Comment (Mingun) [reply src/reader/mod.rs:358]: > Also line 358 should be rewritten - XML isn't "produced" by a parser. You can just say that such documents exist in the wild and are tolerated by some parsers such as the one used by Adobe Flash.

Any help are appreciated :smiley: . I feel that my English is no good to writing simple-to-read explanations.

File: src/reader/mod.rs [hunk 2]
```diff
@@ -345,18 +345,27 @@ macro_rules! read_until_close {
                 }
             },
             // `</` - closing tag
+            // #776: We parse using ElementParser which allows us to have attributes
+            // in close tags. While such tags are not allowed by the specification,
+            // we anyway allow to parse them because:
+            // - we do not check constrains during parsing. This is performed by the
```
Comment (dralley) [inline src/reader/mod.rs:351]: spelling: constraints

File: src/reader/mod.rs [hunk 3]
```diff
@@ -345,18 +345,27 @@ macro_rules! read_until_close {
...
+            //   optional validate step which user should call manually
+            // - if we just look for `>` we will parse `</tag attr=">" >` as end tag
+            //   `</tag attr=">` and text `" >` which probably no one existing parser
+            //   do. This is still invalid tag but it also has no practical meaning
```
Comment (dralley) [inline src/reader/mod.rs:355]: do -> does

File: src/reader/mod.rs (hunk 1 above)
Comment (dralley) [reply src/reader/mod.rs]: That all sounds good to me, but we probably shouldn't document it as a "new feature" given that we do want this to eventually fail for users of the `Reader` API.

File: src/reader/mod.rs (hunk 3 above)
Comment (Mingun) [reply src/reader/mod.rs]: Fixed!

**Review by dralley — APPROVED** [review]

**Comment by Mingun** [comment]
Task CIFuzz was failed by unknown reasons -- I asked https://github.com/google/oss-fuzz/issues/12168 but no response yet... It not related to this changes, so merge
