### PR TITLE
Always use UTF-8 for a `Reader` and a `Deserializer` created from a string

### LINKED ISSUE #324: from_str should ignore encoding in XML declaration
XML can be viewed as a binary format, for instance when parsed using from_reader from a sequence of bytes.
However, when parsing from a &str, the content is already guaranteed to be valid UTF-8.
In that case the encoding hint in the XML declaration should be ignored.

Here is a test that fails (make sure the source code is saved as UTF-8).

```rust
#[test]
fn from_str_should_ignore_encoding() {
    let xml = r#"
        <?xml version="1.0" encoding="windows-1252" ?>
        <A a="€" />
    "#;

    #[derive(Debug, PartialEq, Deserialize)]
    struct A {
        a: String,
    }

    let a: A = quick_xml::de::from_str(xml).unwrap();
    assert_eq!(
        a,
        A {
            a: "€".to_string()
        }
    );
}
```

Test result:
```
---- foo::from_str_should_ignore_encoding stdout ----
thread 'foo::from_str_should_ignore_encoding' panicked at 'assertion failed: `(left == right)`
  left: `A { a: "â‚¬" }`,
 right: `A { a: "€" }`', src/foo.rs:415:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### PR DESCRIPTION
**Pull request by Mingun**
Fixes #324

### CODE REVIEW

File: src/reader.rs [hunk 1]
```diff
@@ -56,6 +56,55 @@ enum TagState {
     Exit,
 }
 
+/// A reference to an encoding together with an information of how it was retrieved.
```
Comment (dralley) [inline src/reader.rs:59]:
```suggestion
/// A reference to an encoding together with information about how it was retrieved.
```

File: src/reader.rs [hunk 2]
```diff
@@ -905,6 +949,15 @@ impl Reader<BufReader<File>> {
 impl<'a> Reader<&'a [u8]> {
     /// Creates an XML reader from a string slice.
     pub fn from_str(s: &'a str) -> Self {
+        // Rust strings a guaranteed in UTF-8, so lock the encoding
```
Comment (dralley) [inline src/reader.rs:952]:
```suggestion
        // Rust strings are guaranteed to be UTF-8, so lock the encoding
```

**Review by dralley — APPROVED** [review]
